### ISSUE TITLE
currencyconverterapi.com: add support for use of an API key

### ISSUE THREAD

**Issue by berendt** [catalyst-cloud/catalystcloud-price-comparison#6]
It looks like it is not longer possible to call http://free.currencyconverterapi.com/api/v5/convert?q=USD_NZD&compact=y without an API key: ``{"status":400,"error":"API Key is required."}``.

According to https://free.currencyconverterapi.com an API key is now required for the free server.

**Comment by berendt** [comment]
And I think ``v6`` has to be used now instead of ``v5``.

**Comment by unexceptable** [comment]
I've switched this a while back to a different exchange API, and fixed this issue. Sorry for not seeing this issue opened.
